version: '3'

services:

  spider_test:
    container_name: spider_test_api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"                                             # Прокидываем порт
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy                              # пока не запуститься База данных не запускать сервис spider_test
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    python manage.py fill_db && \
                    python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: psql
    image: postgres:15.4
    restart: on-failure
    volumes:
      - ./database:/docker-entrypoint-initdb.d                  # sql скрипты из папки database выполнится внутри контейнера
      - spider-data:/var/lib/postgresql/data                    # подмонтированный локальный каталог, из которого данные будут подгружаться в контейнер
    environment:
      POSTGRES_DB: spider_db
      POSTGRES_USER: spider
      POSTGRES_PASSWORD: spider
      PGDATA: "/var/lib/postgresql/data/pgdata"
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spider -d spider_db"]  # проверить соединение с сервером PostgreSQL
      interval: 10s                                             # время в течение которого сервер ждет ответа по тестовой команде
      timeout: 5s                                               # время задержки между проверками
      retries: 5                                                # кол-во сбоев, после которых контейнер считается неработоспособным

volumes:
  spider-data: