version: '3'

services:

  spider_test:
    container_name: spider_test_api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"                                             
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy                              
    command: sh -c "python manage.py makemigrations && \
                    python manage.py migrate && \
                    python manage.py createsuperuser --noinput && \
                    python manage.py fill_db && \
                    python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: psql
    image: postgres:15.4
    restart: on-failure
    volumes:
      - ./database:/docker-entrypoint-initdb.d                  
      - spider-data:/var/lib/postgresql/data                    
    environment:
      POSTGRES_DB: spider_db
      POSTGRES_USER: spider
      POSTGRES_PASSWORD: spider
      PGDATA: "/var/lib/postgresql/data/pgdata"
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spider -d spider_db"]  
      interval: 10s                                             
      timeout: 5s                                               
      retries: 5                                                

volumes:
  spider-data: